version: 0.0
os: linux
files:
  - source: /application.js
    destination: /var/www/html/
  - source: /application.php
    destination: /var/www/html/
  - source: /index.html
    destination: /var/www/html/
  - source: /example.json
    destination: /var/www/html/
  - source: /resources/
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root

